name: "Execute CI/CD Scan"
on:
  pull_request:
    types: [opened, synchronize, closed]
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run GitHub Action
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        DEDGE_HOST_URL: ${{ secrets.DEDGE_HOST_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node actions/github/index.js
