stages:
  - scan

scan_job:
  stage: scan
  image: node:20
  script:
    - curl -LJO https://raw.githubusercontent.com/DSDO01/ci-cd-playground/refs/heads/main/actions/gitlab/dist/index.cjs
    - node index.js
  variables:
    API_TOKEN: dedge_pat_FMcG1zPlT_G_IGZiRTQwEsxXCLO_rVzQNAG-T-pYK9Q=
    DEDGE_HOST_URL: https://scanning.free.beeceptor.com
    GITLAB_TOKEN: $GITLAB_TOKEN_COMMENT ## You must provide it, if you would like to comment on the pull-request.
    ASSET_ID: ac433cef-b387-4142-9c99-4181b46d0b6b
  only:
    - merge_requests
    - main
